src/engine/GameWorker.ts, src/engine/MainThread.ts, src/engine/RenderWorker.ts, src/engine/WorkerMessage.ts, src/engine/stats.ts, src/game.ts, src/ui/hooks/useEngine.ts, src/ui/views/session/SessionView.css, src/ui/views/session/SessionView.tsx
=> Add Stats Panel and Fix Game Worker Scheduling

src/style/flex.css, src/ui/views/session/SessionView.css, src/ui/views/session/SessionView.tsx, src/ui/views/session/room/RoomPreview.css, src/ui/views/session/room/RoomView.css, src/ui/views/session/room/RoomView.tsx, src/ui/views/session/statusbar/StatusBar.css, src/ui/views/session/statusbar/StatusBar.tsx, src/viewModels/session/SessionViewModel.ts, src/viewModels/session/leftpanel/LeftPanelViewModel.ts, src/viewModels/session/statusbar/StatusBarViewModel.ts
Signed-off-by: Ajay Bura <ajbura@gmail.com>
=> Add status bar

src/ui/atoms/avatar/Avatar.tsx, src/viewModels/colorMXID.ts
Signed-off-by: Ajay Bura <ajbura@gmail.com>
=> Show avatar fallback if image don't load

index.html
Mostly doing this to check if netlify is working
=> Change Title

package.json, src/hydrogen-view-sdk.d.ts, src/ui/views/HydrogenRootView.tsx, yarn.lock
Update Hydrogen to the latest [thirdroom/dev branch](https://github.com/vector-im/hydrogen-web/tree/thirdroom/dev)
To Do:
=> Update Hydrogen WIP

src/hydrogen-view-sdk.d.ts, src/ui/atoms/button/IconButton.tsx, src/ui/hooks/useEmbedTimeline.ts, src/ui/hooks/useRoomViewModel.ts, src/ui/views/session/chat/ChatComposer.css, src/ui/views/session/chat/ChatComposer.tsx, src/ui/views/session/chat/ChatTimeline.css, src/ui/views/session/chat/ChatTimeline.tsx, src/ui/views/session/chat/ChatView.tsx, src/ui/views/session/chat/tiles/ChatAnnouncement.css, src/ui/views/session/chat/tiles/ChatAnnouncement.ts, src/ui/views/session/chat/tiles/ChatBaseMessage.css, src/ui/views/session/chat/tiles/ChatBaseMessage.tsx, src/ui/views/session/chat/tiles/ChatGap.css, src/ui/views/session/chat/tiles/ChatGap.ts, src/ui/views/session/chat/tiles/ChatImage.css, src/ui/views/session/chat/tiles/ChatImage.ts, src/ui/views/session/chat/tiles/ChatMessage.css, src/ui/views/session/chat/tiles/ChatMessage.ts, src/ui/views/session/chat/tiles/index.tsx, src/ui/views/session/overlay/WorldPreview.tsx, src/ui/views/session/world-chat/WorldChat.tsx, src/ui/views/session/world-chat/WorldChatTimeline.tsx
This PR add chat timeline (Text message, Membership changes, Image) and ability to send message. Text messages doesn't have custom HTML support and Image message is not tested properly because of cross-origin policy.
=> Chat timeline

src/ui/views/login/LoginView.css, src/ui/views/login/LoginView.tsx
Let me know if there is anything else to improve?
=> Improve login view

src/hydrogen-view-sdk.d.ts, src/ui/views/HydrogenRootView.tsx, src/ui/views/session/SessionView.tsx, src/ui/views/session/create-world/CreateWorld.tsx, src/ui/views/session/overlay/WorldPreview.tsx
=> World preview flow

README.md
=> Add EXT_mesh_gpu_instancing to supported extensions

src/engine/allocator/CursorBuffer.ts, src/engine/audio/audio.main.ts, src/engine/config.game.ts, src/engine/network/NetworkTransformSystem.ts, src/engine/network/network.game.ts, src/engine/physics/physics.game.ts, src/engine/prefab/index.ts, src/plugins/CubeSpawner.ts, src/plugins/FlyCharacterController.ts, src/plugins/GrabThrowController.ts, src/plugins/PhysicsCharacterController.ts, test/engine/network/index.test.ts
- added velocity to networked physics sync
- this fixed weird collisions with other player's objects and the crazy audio spam
- fixed voip
- added velocity-based collision audio
- small cleanup/refactors
=> physics & audio fixes

src/engine/gltf/gltf.game.ts, src/engine/network/network.game.ts, src/engine/network/ownership.game.ts, src/engine/prefab/index.ts, src/plugins/GrabThrowController.ts, src/plugins/PhysicsCharacterController.ts
picking up another player's object takes ownership over it
=> pseudo ownership

package.json, src/ui/App.css, src/ui/App.tsx, src/ui/atoms/input/Input.css, src/ui/atoms/menu/DropdownMenu.css, src/ui/atoms/menu/DropdownMenu.tsx, src/ui/atoms/menu/DropdownMenuItem.css, src/ui/atoms/scroll/Scroll.css, src/ui/style/display.css, src/ui/style/text.css, src/ui/views/components/active-chat-tile/ActiveChatTile.css, src/ui/views/components/avatar-picker/AvatarPicker.tsx, src/ui/views/components/empty-state/EmptyState.css, src/ui/views/components/empty-state/EmptyState.stories.tsx, src/ui/views/components/empty-state/EmptyState.tsx, src/ui/views/components/room-tile/RoomTile.css, src/ui/views/components/window/Window.css, src/ui/views/components/window/Window.tsx, src/ui/views/components/world-preview-card/WorldPreviewCard.css, src/ui/views/session/chat/ChatView.css, src/ui/views/session/create-world/CreateWorld.tsx, src/ui/views/session/dialogs/DmDialog.tsx, src/ui/views/session/dialogs/InviteDialog.tsx, src/ui/views/session/dialogs/JoinWithAliasDialog.tsx, src/ui/views/session/overlay/ActiveChats.css, src/ui/views/session/sidebar/RoomListView.css, src/ui/views/session/sidebar/SpacesView.css, src/ui/views/session/user-profile/UserProfile.tsx, src/ui/views/session/world-settings/WorldSettings.tsx, yarn.lock
=> Fix minor usability

src/ui/hooks/useRoomIdFromAlias.ts, src/ui/views/session/SessionView.tsx
I broke loading the initial world if you hadn't already joined the room or been invited to it. This PR displays the join world WorldPreview when this happens.
=> Fix loading initial world

src/engine/stats/stats.main.ts, src/ui/views/session/stats/Stats.tsx, src/ui/views/session/world/WorldView.tsx
Hiding the stats panel in the console was getting painful so I moved it to a keybinding. Press `ctrl + shift + s` to toggle the stats panel.
=> Change stats hotkey to ctrl+shift+s

package.json, src/hydrogen-view-sdk.d.ts, src/ui/atoms/scroll/Scroll.tsx, src/ui/hooks/usePowerLevels.ts, src/ui/hooks/useRoomMembers.ts, src/ui/views/components/member-tile/MemberTile.css, src/ui/views/components/member-tile/MemberTile.stories.tsx, src/ui/views/components/member-tile/MemberTile.tsx, src/ui/views/components/world-preview-card/WorldPreviewCard.tsx, src/ui/views/session/dialogs/MemberListDialog.tsx, src/ui/views/session/overlay/WorldPreview.tsx, src/ui/views/session/sidebar/RoomListFriends.tsx, src/ui/views/session/sidebar/RoomListHome.tsx, yarn.lock
This PR show members in category(invited, joined, banned and archived) with relevant moderation option like kick, ban, unban, disinvite, invite.
Depends on: https://github.com/vector-im/hydrogen-web/pull/814
=> World member list

netlify.toml, public/.wellknown/matrix/client, public/CNAME, public/well-known/matrix/client
Part of our efforts to implement OIDC login for thirdroom.
=> Add .wellknown to public directory

src/engine/gltf/gltf.game.ts
=> rogue colliders fixed

package.json, yarn.lock
Added @ajbura's fix for a timeline-loading race condition https://github.com/vector-im/hydrogen-web/pull/844
=> Fixed In-World-Chat

public/well-known/matrix/client, src/ui/views/HydrogenRootView.tsx
=> Update homeserver name

src/plugins/thirdroom/thirdroom.game.ts
the actual issue was that we forgot to round the `spawnPointIndex` hehe
=> spawn point fix

res/defaultWorlds.json, src/ui/atoms/thumbnail/Thumbnail.css, src/ui/atoms/thumbnail/Thumbnail.tsx, src/ui/atoms/thumbnail/ThumbnailHover.tsx, src/ui/views/components/avatar-picker/AvatarPicker.tsx, src/ui/views/session/create-world/CreateWorld.tsx, src/ui/views/session/create-world/UploadScene.css, src/ui/views/session/create-world/UploadScene.tsx
Fixes #132 
n.b: Currently we are not selecting defaultRoomAvatarUrl of default scene as hydrogen create room function only accept room avatar as blob
=> Update create world

src/ui/atoms/button/Button.tsx, src/ui/views/HydrogenRootView.tsx, src/ui/views/login/LoginView.tsx
If `guestKeycloakIdpHint` is set then two buttons are shown:
=> Use clientConfigs to determine if separate guest login is available

src/ui/atoms/button/IconButton.tsx, src/ui/views/HydrogenRootView.tsx, src/ui/views/login/LoginView.css, src/ui/views/login/LoginView.tsx
Fixes #206 
Adds a dropdown menu in homeserver input accessible via `ArrowDown` key or clicking on arrow down icon
=> Add homeserver dropdown

src/engine/prefab/prefab.game.ts, src/plugins/thirdroom/thirdroom.game.ts, test/engine/mocks.ts
=> Out of bounds respawn

src/plugins/GrabThrowController.ts, src/ui/hooks/useKeyUp.ts, src/ui/views/session/entity-selected/EntitySelected.tsx, src/ui/views/session/reticle/Reticle.tsx
=> contextual tooltips

src/engine/camera/camera.game.ts, src/engine/camera/camera.render.ts
The glTF camera FOV should be in radians not degrees.
=> Fix world preview camera

src/ui/utils/common.ts, src/ui/views/session/overlay/Overlay.css, src/ui/views/session/overlay/Overlay.tsx
=> Load world preview with blurred thumbnail

package.json, yarn.lock
Fixes outline pass when selecting instanced objects in the editor.
=> Update three to v144

package.json, res/defaultWorlds.json, src/engine/renderer/renderer.common.ts, src/engine/renderer/renderer.game.ts, src/engine/renderer/renderer.render.ts, src/hydrogen-view-sdk.d.ts, src/plugins/thirdroom/thirdroom.game.ts, src/ui/App.tsx, src/ui/hooks/useHomeWorld.ts, src/ui/hooks/useRoomIdFromAlias.ts, src/ui/views/session/home/HomeView.tsx, yarn.lock
=> Home Worlds

vite.config.ts
=> Turn on source maps

.github/workflows/pr.yml, .github/workflows/prod.yml, package.json, src/main.tsx, src/ui/App.tsx, yarn.lock
=> Add Sentry integration

src/engine/network/Historian.ts, src/engine/network/NetworkInterpolationSystem.ts, src/engine/network/network.game.ts, src/ui/views/session/nametags/Nametags.tsx
Alternate to https://github.com/matrix-org/thirdroom/pull/289 while we get hydrogen fixed up
=> Interpolation and nametags fix

src/ui/views/components/world-preview-card/WorldPreviewCard.css, src/ui/views/components/world-preview-card/WorldPreviewCard.stories.tsx, src/ui/views/components/world-preview-card/WorldPreviewCard.tsx, src/ui/views/session/overlay/WorldPreview.tsx
=> Add progress bar in world loading card

package.json, src/hydrogen-view-sdk.d.ts, src/ui/views/HydrogenRootView.tsx, yarn.lock
This helps people differentiate between Hydrogen and Third Room for new client verification alerts.
=> Add Third Room device name

res/defaultWorlds.json
Reduce the number of portals to make finding other users a bit easier
=> Update HomeWorld and default scenes with fewer portals

src/engine/component/transform.ts
=> Fix memory leak caused by resources retained by colliders

src/ui/atoms/avatar/Avatar.tsx, src/ui/views/session/dialogs/MemberListDialog.tsx, src/ui/views/session/sidebar/WorldTileMembers.tsx
=> Fix member pile count text size

src/ui/hooks/useStore.ts, src/ui/views/session/world/WorldLoading.tsx
=> Mute based on user preference

src/ui/atoms/badge/NotificationBadge.tsx, src/ui/views/session/dialogs/MemberListDialog.tsx, src/ui/views/session/nametags/Nametags.tsx
=> Show voice activity in member list

src/asset-pipeline/extensions/OMILinkExtension.ts, src/asset-pipeline/pipeline.ts, src/engine/gltf/OMI_link.ts, src/engine/gltf/gltf.game.ts
Adds support for the draft OMI_link extension https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_link
=> Add support for OMI_link

src/hydrogen-view-sdk.d.ts, src/ui/hooks/useAttachmentUpload.ts, src/ui/utils/common.ts, src/ui/utils/matrixUtils.ts, src/ui/views/components/AutoFileUpload.tsx, src/ui/views/components/file-upload-card/FileUploadCard.tsx, src/ui/views/session/user-profile/UserProfileOverview.tsx, src/ui/views/session/world-settings/WorldSettings.tsx
=> Show error in file upload

src/ui/atoms/input/Input.css, src/ui/views/session/dialogs/InviteDialog.tsx, src/ui/views/session/dialogs/ProfileSuggestion.tsx
=> Improve invite dialog

src/plugins/avatars/common.ts, src/plugins/thirdroom/thirdroom.game.ts, src/ui/views/session/world/ShortcutUI.tsx
Fixes the avatar height, change third person hotkey, and adjust third person offset
=> Fix avatar height

src/engine/RecycleBin.test.ts, src/engine/RecycleBin.ts, src/engine/animation/animation.game.ts, src/engine/config.game.ts, src/engine/network/NetworkAction.ts, src/engine/network/inbound.game.ts, src/engine/network/network.common.ts, src/engine/network/network.game.ts, src/engine/network/network.main.ts, src/engine/network/outbound.game.ts, src/engine/network/serialization.game.ts, src/plugins/nametags/nametags.game.ts, src/plugins/thirdroom/thirdroom.game.ts
- added unreliable network ring buffer
- fixed nametag height
- queued up `onExitWorld` events, fixes networkId recycling bug
=> integration fixes

res/defaultWorlds.json
Updates default worlds to include HDR reflection probes, improved lightmap quality, improved normal maps, and bloom settings.
=> Update default worlds

src/engine/input/ActionMappingSystem.ts, src/plugins/interaction/interaction.game.ts
Not a full fix. But a stopgap for interacting with interactable scripts
=> Fix interactions

src/engine/GameWorker.ts
issue: flickering avatars from firefox browsers
solution: use setTimeout for firefox's game loop
=> timeout gameloop for firefox

src/ui/atoms/menu/MenuItem.css, src/ui/utils/matrixUtils.ts, src/ui/views/session/dialogs/MemberListDialog.tsx
You can now set member power levels from Third Room.
=> Add ability to set power level to member list

src/engine/matrix/matrix.game.ts, src/engine/network/scripting.game.ts
Accidentally was returning the wrong packet/event sizes
=> Return last packet/event size not first

src/plugins/avatars/getAvatar.ts
=> fixed getAvatar function

package.json, src/engine/MainThread.ts, src/engine/light/light.render.ts, src/engine/material/material.render.ts, src/engine/reflection-probe/reflection-probe.render.ts, src/engine/renderer/RenderPipeline.ts, src/engine/renderer/renderer.common.ts, src/engine/renderer/renderer.main.ts, src/engine/renderer/renderer.render.ts, src/ui/views/components/property-panel/SelectInput.tsx, src/ui/views/session/user-profile/UserProfileOverview.tsx, vite.config.ts, yarn.lock
=> Graphics quality setting and auto-detect

src/engine/audio/audio.main.ts, src/engine/resource/RemoteResourceClass.ts, src/engine/resource/ResourceDefinition.ts, src/engine/resource/schema.ts, test/engine/network/index.test.ts
=> fixed skipLerp causing visual glitches on-spawn

src/ui/views/components/property-panel/SelectInput.tsx
=> Fix select input button type

src/ui/hooks/useLocalStorage.ts, src/ui/hooks/useWorldInteraction.ts, src/ui/views/gltf-viewer/GLTFViewer.tsx, src/ui/views/session/entity-tooltip/EntityTooltip.tsx, src/ui/views/session/overlay/NowPlayingWorld.tsx, src/ui/views/session/reticle/Reticle.tsx, src/ui/views/session/sidebar/selector/WorldSelector.tsx, src/ui/views/session/world/WorldControls.tsx, src/ui/views/session/world/WorldInteraction.tsx, src/ui/views/session/world/WorldOnboarding.tsx, src/ui/views/session/world/WorldView.tsx
This PR added options to open invite, chat in now playing screen and refactor `WorldView` component in smaller reusable components.
=> Fix world UX

src/ui/hooks/useWorldLoader.ts
group calls were not being created if they did not already exist. this pr fixes that
=> fixed new world first join load bug

docs/protocol/implementation.md, docs/protocol/index.md, src/engine/input/WebXRAvatarRigSystem.ts, src/engine/network/commands.game.ts, src/engine/network/inbound.game.ts, src/engine/network/network.game.ts, src/engine/network/outbound.game.ts, src/engine/network/ownership.game.ts, src/engine/network/scripting.game.ts, src/engine/network/serialization.game.ts, src/plugins/camera/CameraRig.game.ts, test/engine/network/index.test.ts
Adds spec for the next version of the Third Room networking protocol + small refactor to serialization
=> Networking v3 Docs / Spec

src/ui/views/session/whats-new/special/WebSceneGraphDialog.tsx
hotfix for websg tutorial text on prod
=> Fix WebSG Tutorial Text - Prod
