matrix-org/thirdroom

package.json
yarn.lock

Still waiting on updated typescript definitions. Upgraded `@types/three` from `0.138.0` to `0.139.0` and typechecking passes.
Will update types to `0.140` when https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60143 is released.

Update three.js to v140

---

src/hydrogen-view-sdk.d.ts
src/ui/hooks/useRoomBeingCreated.ts
src/ui/hooks/useStore.ts
src/ui/views/session/SessionView.tsx
src/ui/views/session/overlay/Overlay.tsx
src/ui/views/session/overlay/WorldPreview.tsx
src/ui/views/session/statusbar/StatusBar.tsx
src/ui/views/session/world/WorldView.tsx

This PR is some additional refactoring of @ajbura's last PR.
- Moved from module scoped actions to actions on the state object based on some of the best practices mentioned in the Zustand docs
- Further split out state into slices so that state selectors are easier to write and only select the state you actually want to update your view
- Added some additional logic around room creation / initial room loading / room preview that fixes a few edge cases

More refactoring of global state

---

src/ui/hooks/useStore.ts
src/ui/views/session/overlay/Overlay.tsx
src/ui/views/session/overlay/WorldPreview.tsx
src/ui/views/session/sidebar/RoomListHeader.tsx
src/ui/views/session/sidebar/SidebarView.tsx

This PR disables the Spaces bar while we're waiting on spaces support in Hydrogen and a proper "Explore" page for Third Room. We'll likely bring it back when it's ready. For now, I've disabled it.
I also removed the settings tab completely. I think we should move this under the user dropdown menu. It already has logout and profile options there. Let's move settings under there as well.

Disable Spaces bar and remove Settings tab

---

src/engine/gltf/MX_tiles_renderer.ts

I missed one thing in the last PR. This fixes loading tiles from a relative url rather than the hardcoded path I had in there.

Fix loading tiles from relative url

---

package.json
yarn.lock

There were some issues with basing my changes to 3d-tiles-renderer on the main branch so I've downgraded and things seem to be working much better

Downgrade 3d-tiles-renderer to v0.3.9

---

src/engine/gltf/GLTF.ts
src/engine/gltf/gltf.game.ts
src/engine/mesh/mesh.common.ts
src/engine/mesh/mesh.game.ts
src/engine/mesh/mesh.render.ts
src/engine/node/node.common.ts
src/engine/node/node.game.ts
src/engine/node/node.render.ts
src/engine/renderer/renderer.render.ts

This PR adds support for the [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing) glTF extension. It allows for improved performance when rendering multiple of the same object.
This PR doesn't yet add collision support for instanced meshes (I'm not so sure we should). It also doesn't have support for skinned meshes or updating the properties of instanced meshes yet.

Add support for the EXT_mesh_gpu_instancing extension

---

src/engine/accessor/accessor.game.ts
src/engine/audio/audio.game.ts
src/engine/bufferView/bufferView.game.ts
src/engine/camera/camera.game.ts
src/engine/component/transform.ts
src/engine/gltf/MX_tiles_renderer.ts
src/engine/gltf/gltf.game.ts
src/engine/image/image.game.ts
src/engine/light/light.common.ts
src/engine/light/light.game.ts
src/engine/material/material.game.ts
src/engine/mesh/mesh.game.ts
src/engine/network/network.game.ts
src/engine/node/node.game.ts
src/engine/prefab/index.ts
src/engine/resource/resource.game.ts
src/engine/sampler/sampler.game.ts
src/engine/scene/scene.game.ts
src/engine/texture/texture.game.ts
src/engine/tiles-renderer/tiles-renderer.game.ts
src/plugins/CubeSpawner.ts
src/plugins/thirdroom/thirdroom.common.ts
src/plugins/thirdroom/thirdroom.game.ts
src/plugins/thirdroom/thirdroom.main.ts
test/engine/component/transform.test.ts

We're not properly disposing of resources across the various threads. This PR cleans up resources automatically when you remove entities they are attached to.
To Do:
- Could just be that the physics world has high overhead on top of our various component stores
- Is this just room avatars/previews or is it also textures?

Properly dispose of resources

---

package.json
src/ui/App.css
src/ui/App.tsx
yarn.lock

Uses https://fontsource.org/fonts/inter package instead of google cdn

Replace font from cdn to package

---

src/engine/mesh/mesh.render.ts

We were forcing environment maps and reflection probes to be turned on for MeshBasicMaterial which doesn't support reflection probes. Now we check to see what material it is before turning them on.

Fix MeshBasicMaterial

---

src/asset-pipeline/functions/compressTextures.ts

Using UASTC for RGBM encoded textures still needs some work in the Basis Encoder. Maybe there's another way to do compressed HDR textures but for now we'll move back to using PNGs
https://community.arm.com/arm-community-blogs/b/graphics-gaming-and-vr-blog/posts/high-quality-rgbm-texture-compression-with-astc

Move back to using PNG for RGBM encoded lightmaps

---

src/engine/GameTypes.ts
src/engine/GameWorker.ts
src/engine/MainThread.ts
src/engine/RenderWorker.ts
src/engine/module/MockMessageChannel.ts
src/engine/network/network.game.ts
src/engine/network/network.main.ts
src/engine/renderer/renderer.main.ts
src/engine/renderer/renderer.render.ts

This PR fixes loading Third Room in Safari by using a mocked MessageChannel interface to post messages between workers and when both the MainThread and RenderWorker are ran on the MainThread. Safari cannot properly `postMessage` `SharedArrayBuffer` objects over `MessageChannel` and this works around that bug.

Fix Safari

---

src/engine/renderer/renderer.render.ts

Enable logarithmic depth buffer in Chrome on M1 Mac with OpenGL Backend

---

src/ui/views/session/nametags/Nametags.tsx
src/ui/views/session/world/WorldView.tsx

fixes nametags permanently disappearing when overlay is opened, as well as a few other edge cases
Fixes #228

nametag overlay bugfix

---

netlify.toml

This may address CORS concerns for calls to sentry.tools.element.io

Add CORS header for Sentry

---

src/engine/gltf/MX_reflection_probes.ts
src/engine/material/patchShaderChunks.ts

I don't know what I'm doing, but this appears to do a thing.
It's also not perfect, but it's at least reflecting the environment back rather than acting as a spherical window.

Fix reflections being the wrong way around

---

res/defaultWorlds.json
src/ui/hooks/useHomeWorld.ts
src/ui/views/session/SessionView.tsx
src/ui/views/session/create-world/CreateWorld.tsx
src/ui/views/session/overlay/Overlay.tsx
src/ui/views/session/world-settings/WorldSettings.tsx

This PR ensures we're using the right namespaced world state event. You'll need to go into the world settings, make a modification, hit save to update the world. Or create a new one if you're not interested in it anymore. Homeworlds should migrate automatically.

Migrate m.world -> org.matrix.msc3815.world

---

src/ui/views/session/SessionView.tsx

There shouldn't be any need to navigate back to the home route when transferring worlds. We can just terminate the last network connection and load up the new world. Everything else should be handled automatically. This prevents thrashing the UI more than we have to and rapidly loading and disposing of the home world.

Improve transferring between worlds

---

src/engine/resource/resource.common.ts

This should hopefully resolve issues where module dependencies timeout because they take longer than 3 seconds to load. This bumps the timeout to 30 seconds.

Increase timeout for module dependencies

---

sw.ts

This PR adds service worker cache busting, caching on request object instead of URL, cloning the request just in case, and propagating/logging errors.

Service Worker Caching Improvements

---

src/ui/views/session/SessionView.tsx
src/ui/views/session/overlay/WorldPreview.tsx

Fixes #401 
Note that this doesn't completely fix the `JoinWorldCard` component. The local loading state never results in the `Joining...` message being shown because the parent component changes.
It works alright for now, but I left some TODOs because the fallback `Joining Room...` state might be invalid in certain cases.

Fix joining via url

---

src/ui/views/session/world/WorldView.tsx

If a portal points at a uri that isn't a `matrix:` uri it'll navigate to that page.

Allow for portals to any uri

---

src/asset-pipeline/extensions/OMIColliderExtension.ts

Found a small bug when writing up the latest OMI_collider spec. Should fix some collisions in some scenes

Fix reading OMI_collider height in glTF-transform

---

src/plugins/interaction/interaction.game.ts

This resets the `pressed`/`released` state for all the interactables once per frame instead of once per player rig.

Fix interactable for multiple players

---

examples/presentation/js/presentation-example.js

Use getMaterialByName to fetch texture instead of getTextureByName since the optimizer strips texture names when compressing textures.

Fix presentation example

---

src/ui/hooks/useThrottle.ts
src/ui/utils/matrixUtils.ts
src/ui/views/components/AutoFileUpload.tsx

The upload bar sometimes would get stuck and not update until after an upload had finished. This is because the upload box was using a debounced setState function instead of a throttled function.

Fix upload progress by switching from useDebounce to useThrottle

---

src/plugins/thirdroom/thirdroom.game.ts

Looks like we forgot to flip this back on after working on the editor. Oops! This should fix the recent performance regression.

Re-enable isStatic for environment

---

src/plugins/thirdroom/thirdroom.game.ts

Speeds up engine initialization times and decreases the likelihood that we time out during loading modules.

Don't wait for avatar model to load in module initialization

---

src/ui/views/session/world/MainMenuRootView.tsx
src/ui/views/session/world/WorldLoading.tsx

if anything goes permanently wrong with the room state for some reason (like uploading an invalid file somehow), there was no way to get out of the error state except refreshing. this adds an exit button and fixes the error display

Error display fix & escape hatch

---

src/engine/physics/physics.game.ts
src/engine/resource/RemoteResources.ts

Rigid bodies are accessed by reference `node.physicsBody.body`, while colliders are separately accessed via the `handleToEid` mapping.
Physics body adds/removes were involving rigidbody handles in the `handleToEid` mapping, which caused disposals to delete colliders belonging to other objects.

Physics body handle mapping bugfix
